dist: trusty
sudo: false # container-based

language: php

php:
  - 7.1

services:
  - postgresql

addons:
  postgresql: '9.6'

before_script:
  - travis_retry composer install --prefer-dist
  - cp config/config.local.neon.travis config/config.local.neon
  - psql -c 'create database travis_ci_test;' --username=postgres

script:
  - bin/console migrations:continue
  - bin/ci

cache:
  directories:
    - vendor

notifications:
  email: false
  slack:
    secure: eI2iukZTyVLnwz0WUGWqTxPW8yQxMZ8L0O/OymASCMuQXLU3o0BqbF8FTRyciapySCn47StwsP5G20VCMnr5tlTtE88H1A5m5vJrGKRGCnE/mG2kv5SrF+6SRY8WP4p88HljyN0F4ir4RyFyQXzZdQWmbaYk9LJhdQ0uqtayJdUinh7SaDqvO4vA/Aop2J5wRp3rojwDICpcVOPCFk+C5ZrFqecvmPRySkwjMm2VxANlSRNkn9e5XhKgoC2Cgzhip9RqMtH5XyCd6Jx9ZGblwyTlDb0Tgs2WOVkIEe5LIWwXqLA/fbHHD01i2MqLI4/F72HHF+jTNbd7xU5DXA/OUN1jramJYZxaJJ03dEYEvcYp44D/Don70ajufE7E3Fbj4DM7koASFoOLsmlkdr2zo8rf4gU6/uuHUt2Ys4tupPUI+JoByNfU80TeNqvVGZgDVCoBTaS6O6o2BpgGGbVAO6KZBY+oB1ycYxBehqKOUcSA4JmNGTFlwltuv52/l0BTkLYpeuQqogSev8zORrBnP0Vd8XPBpgzS/ns++1Kuv5BUHTkRMAfe9/ucu26guhspLmXLFM4XIXblWQ1vimMTnbk/swaE1pJSl7dpDJTQ8pLzPgqZ42qviMMU+rfzfrRXBVs3hOQ0N3/8aptvYKj0/zqqQDQIUZYlVb9IxWos5Qo=
