language: php

php:
  - 7.0
  - 7.1

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - travis_retry composer install --prefer-dist
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/config.local.neon.travis config/config.local.neon

script:
  - vendor/bin/parallel-lint . -e php,php3,php4,php5,phtml,phpt --exclude vendor --blame
  - tests/run
  - bin/console orm:validate-schema
  - vendor/bin/phpcs --standard=ruleset.xml --extensions=php --encoding=utf-8 --tab-width=4 -sp src/ --ignore=bootstrap.php
  - vendor/bin/phpcs --standard=ruleset.xml --extensions=php,phpt --encoding=utf-8 --tab-width=4 -sp tests/ --ignore=*/output/*,_temp/*,bootstrap.php

cache:
  directories:
    - vendor

notifications:
  email: false
