language: php

php:
  - 7.1

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - travis_retry composer install --prefer-dist
  - cp config/config.local.neon.travis config/config.local.neon
  - psql -c 'create database travis_ci_test;' --username=postgres

script:
  - vendor/bin/parallel-lint . -e php,php3,php4,php5,phtml,phpt --exclude vendor --blame
  - tests/run
  - vendor/bin/phpstan analyse --level 5 extensions migrations src tests/extensions tests/src tests/utils
  - bin/console orm:validate-schema --skip-sync
  - vendor/bin/phpcs --standard=ruleset.xml --extensions=php --encoding=utf-8 --tab-width=4 -sp extensions/ migrations/ src/ --ignore=bootstrap.php
  - vendor/bin/phpcs --standard=ruleset.xml --extensions=php,phpt --encoding=utf-8 --tab-width=4 -sp tests/ --ignore=*/output/*,_temp/*,bootstrap.php

cache:
  directories:
    - vendor

notifications:
  email: false
  slack:
    secure: jFq4mQkKssPzWlzi8rPqul3PBEWPHU38BgTNRgZLV3q9IvnbQXGNOlZXIoDWgf8Mq7yIysrcJnurdZT0KGb7i21271zl6dYji9vEh3Lecc5CpLeL60r9JY6YxUaxZYgYIXrUxjYpsClGQhZKcnKHyy3Sl32QyeKStvsMsDtRrug+oq0mrlG2GMnCsrLODfMH/OJrq+ZVybivhec8veIbO2nvwNeKW3facvha4S0ZWPmdMZ8Yr3+Yy0Uz8iR/i26qCtqfRoEZYTawRMRVOcvBX2xsFCskuhvpNXjYZIGpVTtw/G7eO77AQXQTK1tWa5XLb93MTyFsbDRimHUJfSlp3qquhwUKdv4KFggIyCJ0CtlJqswJvN39wfzJbyuwxW5ALt/N2EjPH83z/3pVbhL3uztjpnXux75JpnrNrTKUh2pWYBEZv4JHtS5IVq9eaY1zLak7mz9+2uOCULaAaZobRHvrPLZxn++DKU8/JkyfVHcDVX7c/tRT/oslOEt4clYWQCBAO+v1XFvDGlXHT6vF25sQp5FsyLFA+5J4f5dBNwKMYLRgxaOOk2trV6NaxWguCev/JWKEgJRwtZyPZg3voYCL8pdqpFrxS/LjD8El+IsLJR+8DpCHfSna+5vto3cEtPB+1qOUHXSmnMFZQJfTY18ddQRtmTdvOHTt/9D+rY0=
    on_success: change
    on_failure: always
